[package]
name = "rust-app"
version = "0.1.0"
edition = "2024"
rust-version = "1.99.0"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
tracing = "0.1"
tracing-subscriber = {
  version = "0.3",
  features = [
    "env-filter",
    "tracing-log",
  ]
}

[lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
codegen-units = 1

[profile.profiler]
inherits = "release"
debug = true
split-debuginfo = "unpacked"
strip = "none"
