[package]
name = "rust-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
rust-lib = { path = "../lib" }
tracing.workspace = true
tracing-subscriber = {
  version = "0.3",
  features = [
    "env-filter",
    "tracing-log",
  ]
}

[lints]
workspace = true
